server:
  port: 9001
spring:
  application:
    name: demo-eureka
  security:
    user:
      name: admin
      password: admin

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defalutZone: http://${eureka.instance.hostname}:${server.port}/eureka/

